### PR TITLE
Update Example 2 to match the tutorial

### PR DESCRIPTION
**Pull request by thelfer**

### CODE REVIEW

**Comment by latug0** [comment]
Is this branch ready for merge ?_

**Comment by thelfer** [comment]
Yes !

**Comment by latug0** [comment]
Problem for compiling this branch.
>  problem.addPostProcessing("ParaviewExportIntegrationPointResultsAtNodes",
>                           {{{"Results", "FirstPiolaKirchhoffStress"},
>                             {"OutputFileName", "ssna303-stress"}}});

FirstPiolaKirchhofStress is not defined.

**Comment by thelfer** [comment]
This is only the case if your are in small strain !
In this case, you shall replace FirstPiolaKirchhoffStress by Stress.
Thomas

**Pull request merged**
