### PR TITLE
Add new example

### PR DESCRIPTION
**Pull request by thelfer**
This pull request introduce a new test which models a 2D plate of length 1 in plane strain clamped on the left and right boundaries and submitted to a parabolic thermal gradient along the x-axis:

- The temperature profile is minimal on the left and right boundaries
- The temperature profile is maximal for x = 0.5

This example shows how to define an external state variable using an analytical profile.

This pull request contains also additional consistency checks to compile some tests only if MFEM was compiled with the correct eatures (example: only compile parallel code if MFEM_USE_MPI is defined).

### CODE REVIEW

**Comment by latug0** [comment]
I don't understand why there are modifications in the  `ex1\ directory ...
Why have you push your `env.sh` files in several directories ?

**Comment by latug0** [comment]
Why did you add two files in `ex3`  ?

**Comment by thelfer** [comment]
I did not meant to. I believe that those files came from a merge with your master branch...

**Comment by latug0** [comment]
> I did not meant to. I believe that those files came from a merge with your master branch...

I don't think so, my commit `5c09436` just changes only one single file ...

**Comment by latug0** [comment]
In the env.sh files, your home directory is mentioned.

**Comment by thelfer** [comment]
Strange. `ImmutablePartialQuadratureFunctionView` is defined in `PartialQuadratureFunction.hxx` as shown here: https://github.com/thelfer/mfem-mgis/blob/c905d52652303de2a190a174ea4aa903c655897d/include/MFEMMGIS/PartialQuadratureFunction.hxx#L102

**Comment by latug0** [comment]
> Strange. `ImmutablePartialQuadratureFunctionView` is defined in `PartialQuadratureFunction.hxx` as shown here: https://github.com/thelfer/mfem-mgis/blob/c905d52652303de2a190a174ea4aa903c655897d/include/MFEMMGIS/PartialQuadratureFunction.hxx#L102

Sorry, my bad : 1) I forgot to update tfel and mgis packages which is required, 2) I had two `mfem-mgis` install directories that were in conflict. I am now able to compile and run `ex5` example.

If you can reshape your pull request to keep only contributions in `ex5` and `ex3` directories, it would be great.

**Comment by thelfer** [comment]
Ok. I'll step back on the other files and will provide the corrections to the other directories in dedicated PR.

**Comment by latug0** [comment]
A few fixes proposed in #8. Do you agree ?

**Comment by latug0** [comment]
solved by #8

**Pull request closed without merging**
